---
title: "Assessment1-Part1"
author: "Yalan S4664845"
date: "05/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## RMarkdown editing 

#_**R Markdown provides an unified authoring framework for data science, combining your code, its results, and your prose commentary. R Markdown documents are fully reproducible and support dozens of output formats, like PDFs, Word files, slideshows, and more.**_

#how to insert a link: [here](https://rmarkdown.rstudio.com/lesson-8.html)

#Insert an R chunk and create an variables with dataset
```{r}
#install.packages("tidyverse")
library(tidyverse)
#install.packages("skimr")
library(skimr)
library(knitr)

#load the dataset from [link](https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-09-04/fastfood_calories.csv)

fastfood_calories <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-09-04/fastfood_calories.csv')

#create a variable with dataset named "fastfood"
Fastfood_calories <- fastfood_calories %>%
  mutate(Fastfood = "Fastfood")

#Display the first 10 rows of the data set

head(Fastfood_calories,10)
kable(Fastfood_calories[1:10,1:19])

#Display the first 10 rows of the dataset and the first 5 variables

kable(Fastfood_calories[1:10,1:5])
```

